

services:
  geth:
    image: ethereum/client-go:v1.17.1@sha256:66eee4d024e0f8ef180f1fa9578cfaccb5926d543f315f6d7d609a71aa644873
    container_name: ethereum
    command:
      - --mainnet
      - --datadir=/opt/ethereumd/.ethereum
      - --ws
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/opt/ethereumd/.ethereum/jwt.hex
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - eth-mainnet-data:/opt/ethereumd/.ethereum
      - ./jwt.hex:/opt/ethereumd/.ethereum/jwt.hex

  beacon:
    image: gcr.io/offchainlabs/prysm/beacon-chain:v7.1.3@sha256:2d98a33e10265c9c91a9dce8cc694d69ce1032c94c8b185df06054d71926c062
    container_name: beacon
    command:
      - --mainnet
      - --disable-last-epoch-targets
      - --config-file=/opt/ethereumd/data/beacon.yaml
    ports:
      - 3500:3500
      - 12000:12000
    volumes:
      - eth-mainnet-data:/opt/ethereumd/data
      - ./beacon.yaml:/opt/ethereumd/data/beacon.yaml
      - ./jwt.hex:/opt/ethereumd/data/jwt.hex

volumes:
  eth-mainnet-data:
