name: verifier-doge

x-django: &django
  image: ghcr.io/flare-foundation/verifier-utxo-indexer:v1.1.0@sha256:410dac33f9168e589694ef62da2010f4f0705e9e3d59a2638ad0dcd9b7797557
  env_file:
    - indexer.env
  environment:
    DB_PORT: 5432
    DB_HOST: database
  volumes:
    - doge-indexer-static:/appdata/static
    - doge-indexer-media:/appdata/media
  restart: unless-stopped
  depends_on:
    database:
      condition: service_healthy

x-django-management: &django-management
  <<: *django
  stop_signal: SIGINT
  depends_on:
    database:
      condition: service_healthy
    indexer-server:
      condition: service_healthy


services:
  database:
    container_name: verifier-doge-database
    image: postgres:18@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    env_file:
      - database.env
    ports:
      - 127.0.0.1:25432:5432
    restart: unless-stopped
    volumes:
      - doge-indexer-database:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      start_period: 60s
      start_interval: 2s

  verifier:
    image: ghcr.io/flare-foundation/verifier-indexer-api:v1.6.0@sha256:d6c9c95da19ac4c34b35be985dbbac89ff31e9c52f8bdf06d09b92bafe1ac987
    container_name: verifier-doge-verifier
    env_file:
      - verifier.env
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 9502:3100

  indexer-server:
    <<: *django
    container_name: verifier-doge-server
    ports:
      - 127.0.0.1:8402:8000
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://127.0.0.1:8000/metrics', timeout=5).raise_for_status()"]
      interval: 60s
      start_period: 60s
      start_interval: 2s

  indexer-indexer:
    <<: *django-management
    container_name: verifier-doge-index-blocks
    command: django-management block_indexing

  indexer-prune:
    <<: *django-management
    container_name: verifier-doge-prune-blocks
    command: django-management block_pruning

volumes:
  doge-indexer-static:
  doge-indexer-database:
  doge-indexer-media:
