

services:
  dogecoin-node:
    image: ghcr.io/flare-foundation/connected-chains-docker/dogecoind:v1.14.9@sha256:7314b6a42e626dbe125add01bf8aaff73935fb0373e60e0341013362f1dcd970
    container_name: node-mainnet-doge-2
    restart: unless-stopped
    ports:
      - 32555:22555
      - 32556:22556
    volumes:
      - dogecoin-mainnet-data:/opt/dogecoin/.dogecoin/db
      - ./dogecoin.conf:/opt/dogecoin/.dogecoin/dogecoin.conf

volumes:
  dogecoin-mainnet-data:
