services:
  indexer:
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - xrp-node
  verifier:
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  xrp-node:
    external: true
    name: xrp_default
