name: verifier-xrp

services:
  database:
    container_name: verifier-xrp-database
    image: postgres:18@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    env_file:
      - database.env
    ports:
      - 127.0.0.1:25433:5432
    restart: unless-stopped
    volumes:
      - xrp-indexer-database:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      start_period: 60s
      start_interval: 2s

  indexer:
    container_name: verifier-xrp-indexer
    image: ghcr.io/flare-foundation/verifier-xrp-indexer:v2.0.0-rc.0@sha256:2c6940e2d90be458605a4d9aab665577d9a5bad15acd5ffbea15493da3dd01a0
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml

  verifier:
    image: ghcr.io/flare-foundation/verifier-indexer-api:v1.5.0-rc.2@sha256:c52c407c80649065b2d82638e2a480595c2cc082f3911f7d2f4d7502738c916a
    container_name: verifier-xrp-verifier
    env_file:
      - verifier.env
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 9503:3100


volumes:
  xrp-indexer-database:
