services:
  web2-verifier:
    image: ghcr.io/flare-foundation/verifier-indexer-api:v1.6.0@sha256:d6c9c95da19ac4c34b35be985dbbac89ff31e9c52f8bdf06d09b92bafe1ac987
    container_name: web2-verifier
    restart: unless-stopped
    ports:
      - 9801:3100
    env_file:
      - verifier.env
