services:
  evm-verifier:
    image: ghcr.io/flare-foundation/evm-verifier:v1.0.3
    container_name: evm-verifier
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 9800:9800
    env_file:
      - verifier.env
