x-verifier: &verifier
  image: ghcr.io/flare-foundation/verifier-indexer-api:v1.6.1@sha256:5bd9717dad96aca2f119eb95304857f8a0bfa1b4d196ef1aaa0889cc490dcc50
  restart: unless-stopped

services:
  verifier_eth:
    <<: *verifier
    environment:
      VERIFIER_TYPE: eth
      APP_BASE_PATH: /verifier/eth
    env_file:
      - verifier.env
      - verifier-eth.env
    ports:
      - "9701:9700"

  verifier_flr:
    <<: *verifier
    environment:
      VERIFIER_TYPE: flr
      APP_BASE_PATH: /verifier/flr
    env_file:
      - verifier.env
      - verifier-flr.env
    ports:
      - "9702:9700"

  verifier_sgb:
    <<: *verifier
    environment:
      VERIFIER_TYPE: sgb
      APP_BASE_PATH: /verifier/sgb
    env_file:
      - verifier.env
      - verifier-sgb.env
    ports:
      - "9703:9700"
