name: verifier-btc-2

x-django: &django
  image: ghcr.io/flare-foundation/verifier-utxo-indexer:v1.0.2@sha256:42b2f5b1af89cf28e437a04f7d7bbbd8dd8afc708c29f56102551eb9c717b909
  env_file:
    - indexer.env
  environment:
    DB_PORT: 5432
    DB_HOST: database
  volumes:
    - btc-indexer-static:/appdata/static
    - btc-indexer-media:/appdata/media
  restart: unless-stopped
  depends_on:
    database:
      condition: service_healthy

x-django-management: &django-management
  <<: *django
  depends_on:
    database:
      condition: service_healthy
    indexer-server:
      condition: service_healthy


services:
  database:
    container_name: verifier-btc-database-2
    image: postgres:18@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    env_file:
      - database.env
    ports:
      - 127.0.0.1:35431:5432
    restart: unless-stopped
    volumes:
      - btc-indexer-database:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      start_period: 60s
      start_interval: 2s

  verifier:
    image: ghcr.io/flare-foundation/verifier-indexer-api:v1.2.2@sha256:e8a94dd88276c0c06f44af561d9e3f06a42c405409c1002811015993cde377ca
    container_name: verifier-btc-verifier-2
    env_file:
      - verifier.env
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 19501:3100

  indexer-server:
    <<: *django
    container_name: verifier-btc-server-2
    ports:
      - 127.0.0.1:18401:8400
    healthcheck:
      test: ["CMD", "curl", "-s", "--fail", "-o", "/dev/null", "http://127.0.0.1:8400/metrics"]
      interval: 60s
      start_period: 60s
      start_interval: 2s

  indexer-indexer:
    <<: *django-management
    container_name: verifier-btc-index-blocks-2
    command: django-management block_indexing

  indexer-prune:
    <<: *django-management
    container_name: verifier-btc-prune-blocks-2
    command: django-management block_pruning

volumes:
  btc-indexer-static:
  btc-indexer-database:
  btc-indexer-media:
