services:
  database:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  verifier:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  indexer-server:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  indexer-indexer:
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
