

services:
  ripple-node:
    image: ghcr.io/flare-foundation/connected-chains-docker/xrpl:3.2.0@sha256:a64363903662e6b70c9e1241b12b1589bfea1903f1dc9fc958468cef9c6931da
    container_name: node-mainnet-xrp
    restart: unless-stopped
    ports:
      - 2459:2459   # port_peer
      - 51234:51234 # port_rpc_public
      - 51233:51233 # port_ws_public
    volumes:
      - ripple-mainnet-data:/opt/xrpld/.xrpld/db
      - ./xrpld.cfg:/opt/xrpld/.xrpld/xrpld.cfg
      - ./validators.txt:/opt/xrpld/.xrpld/validators.txt

volumes:
  ripple-mainnet-data:
