

services:
  ripple-node:
    image: ghcr.io/flare-foundation/connected-chains-docker/rippled:3.1.2@sha256:baeea4cd55087ae0b2400357d5bf3f241762bff59ff37f19085e273ab148af3c
    container_name: node-mainnet-xrp-2
    restart: unless-stopped
    ports:
      - 127.0.0.1:15005:5005   # port_rpc_admin_local
      - 16006:6006   # port_ws_admin_local
      - 61235:51235 # port_peer
      - 61234:51234 # port_rpc_public
      - 61233:51233 # port_ws_public
      - 60051:50051 # port_grpc
    volumes:
      - ripple-mainnet-data:/opt/ripple/.ripple/db
      - ./rippled.conf:/opt/ripple/.ripple/rippled.conf
      - ./validators.txt:/opt/ripple/.ripple/validators.txt

volumes:
  ripple-mainnet-data:
